"""Add cascade delete to blog relationships

Revision ID: 24f37125a706
Revises: 9a3a4592f71b
Create Date: 2025-10-13 18:41:02.157778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f37125a706'
down_revision: Union[str, Sequence[str], None] = '9a3a4592f71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_likes_blog_id_fkey'), 'blog_likes', type_='foreignkey')
    op.create_foreign_key(None, 'blog_likes', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_blog_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_blog_id_fkey'), 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_constraint(None, 'blog_likes', type_='foreignkey')
    op.create_foreign_key(op.f('blog_likes_blog_id_fkey'), 'blog_likes', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###
